version: '3'

services:
  dbpostgres:
    image: postgres:9.6.8-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: opencollective_dvl
    volumes:
      - /tmp/postgres:/var/lib/postgresql  
    ports:
        - "5433:5432"  
  migration:
    build: .
    command: bash -c "npm install && npm run db:migrate"
    ports:
        - "3065:3070"
    depends_on:
      - dbpostgres 
    environment:
      NODE_ENV: docker
      TZ: UTC
      DB_NAME: opencollective_dvl
      DB_URL: postgres://postgres:postgres@dbpostgres:5432/opencollective_dvl
      DB_HOST: dbpostgres
      DB_USER: postgres
      DB_PORT: 5432
      SKIP_WORKERS: 1
      DB_PASS: postgres
      DB_TYPE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      WAIT_HOSTS: dbpostgres:5432
  ledger:
    build: .
    command: npm run start
    ports:
        - "3070:3070"
    depends_on:
        - dbpostgres
        - migration
    environment:
      NODE_ENV: docker
      TZ: UTC
      DB_NAME: opencollective_dvl
      DB_URL: postgres://postgres:postgres@dbpostgres:5432/opencollective_dvl
      DB_USER: postgres
      DB_PORT: 5432
      DB_HOST: dbpostgres
      SKIP_WORKERS: 1
      DB_PASS: postgres
      DB_TYPE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      WAIT_HOSTS: dbpostgres:5432
      
  