version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.3.0
        command: /sbin/init
      - image: circleci/postgres:9.6.8-alpine-postgis-ram
        environment:
          POSTGRES_USER: 'opencollective'
          POSTGRES_DB: opencollective_dvl
          POSTGRES_PASSWORD: ''
    environment:
      TZ: 'UTC'
      NODE_ENV: 'circleci'
      SEQUELIZE_ENV: 'circleci'
      DB_NAME: 'opencollective_dvl'
      DB_USER: 'opencollective'
      DB_PORT: 5432
      DB_PASS: ''
      DB_TYPE: 'postgres'
      POSTGRES_USER: 'opencollective'
      POSTGRES_DB: opencollective_dvl
      POSTGRES_PASSWORD: ''
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: sudo apt -y update
      - run: sudo apt -y install postgresql-client    
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run test
      - store_test_results:
          path: /tmp/circleci-test-results
    branches:
      ignore:
        - heroku
        - staging
        - production